### ISSUE TITLE
How do I execute a custom command when Alexa is triggered?

### ISSUE THREAD

**Issue by mcosti** [alexa-pi/AlexaPi#252]
Hello. I have some wireless lights that have python libraries to control them with.
Can you please tell me how do I trigger the light when Alexa is ready to listen to me?

Thank you very much!

**Comment by EmerickH** [comment]
Hello,
Create first Python scripts to on/off your lights
Then in your config file there's a category to start commands before/after trigger.
Example:
```
# Commands to run before and after an interaction begins. Leave empty to disable.
event_commands:

  # Command to run at the start of AlexaPi
  startup: ""

  # Command to run after a trigger is detected but before an interaction begins
  pre_interaction: "python /my/folder/startlight.py"

  # Command to run after the interaction has completed
  post_interaction: "python /my/folder/stoplight.py"

  # Command to run during a clean shutdown of AlexaPi
  shutdown: ""
```

Emerick
