### ISSUE TITLE
Beep feedback?

### ISSUE THREAD

**Issue by usamitysam** [alexa-pi/AlexaPi#261]
Am I supposed to hear beep feedback on things like: done listening, giving up listening, couldn't understand, misc error, etc?  Every once in a while I hear a beep at the end of an interaction but not normally.

**Comment by EmerickH** [comment]
Hello,
I think there's no beep, just "hello" when starting and "yes" when triggered if it's activated in config:
```
pocketsphinx:
    enabled: true
    voice_confirm: true
```
or if you're using GPIO trigger:
```
triggers:
  platform:
    enabled: true
    voice_confirm: true
```
but if you want to hear them, you can do it manually with aplay command:
```
event_commands:
  # Command to run at the start of AlexaPi
  startup: "aplay resources/beep.wav"
  # Command to run after a trigger is detected but before an interaction begins
  pre_interaction: ""
  # Command to run after the interaction has completed
  post_interaction: "aplay resources/beep.wav"
  # Command to run during a clean shutdown of AlexaPi
  shutdown: "aplay resources/alexahalt.mp3"
```

Emerick
