### ISSUE TITLE
[6c0004d8] alsa audio output error: cannot estimate delay: Input/output error

### ISSUE THREAD

**Issue by wiredwrx** [alexa-pi/AlexaPi#265]
Getting the following error
```
[6c0004d8] alsa audio output error: cannot estimate delay: Input/output error
```

**Your OS (including version) where you are running AlexaPi:**
```
Raspbian Jessie/Pixel. 
Updated today with apt-get update and apt-get install update
```

**Your hardware platform and model you are running on:**
```
Raspberry PI 3
```

**Python release (`python2 --version`):**
```
2.7.9
```

**Description of problem:**
```
Getting the following error
[6c0004d8] alsa audio output error: cannot estimate delay: Input/output error
```

**Problem-relevant `config.yaml` entries:**
```
sound:
  # Name of your ALSA microphone/soundcard in arecord -L
  input_device: "pulse"
  # This is here if none of the listed device: "raspberrypi"
  # This is an override that is normally not needed and is a last resort.
  allow_unlisted_input_device: false

  playback_handler: "vlc"

   # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  output: "pulse"
  # output device: "raspberrypi"
  # currently supports ALSA only
  output_device: ""

  # if left empty, won't be passed to the underlying library / command if it su$
  # if it doesn't 100% will be used
  default_volume: 80

  # Means the same as above, but is used for media (playing music for example)
  # Leave blank to use the same setting as for speech content
  media_output:
  media_output_device:
  media_default_volume:

  # Some device: "raspberrypi"
  # value is the number of seconds of silence to pad the beginning and end of t$
  # the sox handler supports this configuration option.
  playback_padding: 0
```

**Additional info:**
```
This is a brand new install following the instructions form here "http://lifehacker.com/the-simplest-way-to-build-a-raspberry-pi-powered-amazon-1794218212"
```
