### ISSUE TITLE
Alexa will not respond after 3 attempts [NEW]

### ISSUE THREAD

**Issue by AustinErben** [alexa-pi/AlexaPi#289]
**Your OS (including version) where you are running AlexaPi:**
```
Ubuntu Mate 16.04
```

**Your hardware platform and model you are running on:**
```
Raspberry Pi 3 Model B
```

**Python release (`python2 --version`):**
```
Python 2.7.12
```

**Description of problem:**
```
Alexa answers and responds twice and then on third attempt does not respond. We then check on Alexa's status in the terminal and when we close the terminal she will respond to the question and work for another two questions.
```

**Expected:**
```
She can continually answer questions without use of the terminal or rebooting
```

**Problem-relevant `config.yaml` entries:**
```
# See https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging
# to get a better idea of how to set things in here

# Level of log output
# default: INFO
# set to DEBUG for verbose logging
logging: INFO

sound:
  # Name of your ALSA microphone/soundcard in arecord -L
  input_device: "pulse"
  output: "pulseaudio"
  output_device: ""
  # This is here if none of the listed device: "raspberrypi"
  # This is an override that is normally not needed and is a last resort.
  allow_unlisted_input_device: false

  playback_handler: "sox"

  # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  output: "alsa"
  # output device: "raspberrypi"
  # currently supports ALSA only
  output_device: "default"

  # if left empty, won't be passed to the underlying library / command if it supports it
  # if it doesn't 100% will be used
  default_volume: 80
```

**Steps to reproduce:**

1.  Alexa starts at boot
2.  Ask 2 questions, get 2 answers
3. Ask third question, get no response

**Traceback (if applicable):**
```
n/a
```

**Additional info:**
```
We have ran PA system wide and have already ran all audio setups and configured our config.yaml file.
```
