### ISSUE TITLE
Wake Up word Amazon Voice Services Alexa Text

### ISSUE THREAD

**Issue by jinho8067** [alexa-pi/AlexaPi#413]
How to Text Alexa Pie Wake Up Words

**Comment by EmerickH** [comment]
Hello,
I suppose you want to change your wake up word?
Just edit your config.yaml file and change the phrase here:
```yaml
  pocketsphinx:
    enabled: true
    voice_confirm: true

    phrase: "alexa" # <- Change here
    threshold: 1e-10
```
