### ISSUE TITLE
HTTP Error 500 when going to http://raspberryIP:5050

### ISSUE THREAD

**Issue by JacobMeister** [alexa-pi/AlexaPi#422]
I've been stuck on this for a couple of hours and haven't found a fix in any other issue thread.

**Your OS (including version) where you are running AlexaPi:**
```
Raspbian
```

**Your hardware platform and model you are running on:**
```
raspberry pi 3b+
```

**Python release (`python2 --version`):**
```
Python 2.7.13
```

**Description of problem:**
```
Can't reach localhost:5050 or raspberryIP:5050, the page is not working
```

**Expected:**
```
amazon login page
```

**Problem-relevant `config.yaml` entries:**
```
# Amazon Alexa settings
alexa:
  Client_ID: "amzn1.application-oa2-client.3f4eXXXXXXXXXXXXXXXXXXd7"
  Client_Secret: "da984c25XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX75127baa"
  Device_Type_ID: "SchoolProjectPi"
  Security_Profile_Description: "SchoolProjectPi"
  Security_Profile_ID: "amzn1.application.170b26XXXXXXXXXXXXXXXXXXXXXXXd20ef"
  refresh_token:



```

**Steps to reproduce:**

1. Follow instruction manual
2. manually install cherrypy because i get this error => https://github.com/alexa-pi/AlexaPi/issues/415
3. run setup normally
4. go to http://192.168.178.38:5050

**Traceback (if applicable):**
```

```

**Additional info:**
```
I had the cherrypy issue which i solved by installing it manually. The setup script ran without problems after that.
I've doublechecked every single ID and secret, so either i'm blind or something else is wrong.
```
![pi-ip-address](https://user-images.githubusercontent.com/15727299/46815851-08ad1600-cd7c-11e8-85ee-051659729d3c.PNG)

![pi-info](https://user-images.githubusercontent.com/15727299/46815653-9a685380-cd7b-11e8-8300-f743fee9bf76.PNG)
![pi-security-info](https://user-images.githubusercontent.com/15727299/46815656-9a685380-cd7b-11e8-83bd-2f4af5dea7f2.PNG)
![pi-origins-info](https://user-images.githubusercontent.com/15727299/46815655-9a685380-cd7b-11e8-89c1-16a833ae26c7.PNG)
