### ISSUE TITLE
Alexa wake up randomly....and oathers

### ISSUE THREAD

**Issue by Akkor70** [alexa-pi/AlexaPi#433]
Hi
I have a raspian strech latest version
I made the instalation following the guide and all seems going fine
The issue that I'm experiencing are:
1)  Alexa wake up randomly while I'm watching tv or while someone talking....but no words like alexa or echo comes out from tv or voices.....
2) If I ask alexa to decrease volume while I'm listening radio she stops the radio and the volume doesn't change.........
Solutions ?

**Comment by EmerickH** [comment]
Hello,
1. You can try to change the threshold in AlexaPi `config.yaml` or even maybe the wake up phrase:
   ```yaml
    pocketsphinx:
       enabled: true
       voice_confirm: true

       phrase: "alexa"
       threshold: 1e-10
   ```
2. Sorry, I can't help you but all I know is that radio implementation of radio in AlexaPi is buggy because everything is made on the remote API server and not in your device
