### ISSUE TITLE
Snowboy support

### ISSUE THREAD

**Issue by renekliment** [alexa-pi/AlexaPi#53]
We can see progress in this repo, so I'm opening this issue already, even though it's gonna take a while to get there.

After #24 is done, let's also support snowboy (so users can choose, let's not just replace pocketsphinx with it).

@maso27 and @flooie have done this in their repos based on the original project. We can learn from that.

**Comment by renekliment** [comment]
Ah, it seems that snowboy isn't open-source or free (as in freedom). Just stating though, it's not a blocker. Good thing we keep support for pocketsphinx, so people who want to run free software only can run AlexaPi. But those people wouldn't want to use such _evil_ services like AVS. Well, nevermind :smile:

**Comment by renekliment** [comment]
A couple of notes:
- I'd do it as a git submodule - there is no pypi package.
- example config:
```yaml
triggers:
  snowboy:
    enabled: false
    voice_confirm: true

    # rpi, ubuntu64, osx, android-armv7a
    platform: "rpi"

    model: "{distribution}/Alexa.umdl"
```
